title: Annexes de mémoire
subtitle: Agathe KOWALSKI - Master Son 
description: Annexes audio-visuelles du mémoire ENSLL 2026
#theme: minima

baseurl: "/ensll_memoire_p2026/"  # Doit commencer et finir par un slash
url: ""  # Laisse vide si tu utilises GitHub Pages avec un domaine github.io
include: ['audios'] 

markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

